### PR TITLE
video mode

### PR DESCRIPTION
**Pull request by onokatio**
If `video_mode = true`, stop proccess metadata and tags.

### CODE REVIEW

**Comment by michaelb** [comment]
hi onokatio, thanks for contributing, it is a very nice and welcome feature/idea, i was also envisioning something like this in the long run

I will have to modify some parts of your code though, because Windows support is incoming and it means os.system commands must be cross-platform. But your 'mv' commands should be easily translatable :-). You probably also want to overwrite the metadata-from-title  attribute temporarly by setting it to false.


Also, I think you or I should also have to modify the config.py file to provide a video_mode attribute, but that means unfortunately, we'll have to trigger the upgrade system (it ensures that when a old user upgrades, they keep part of their config file, but the rest is created/resetted/removed to be match what the new version expects from config). 

I programmed the upgrade system to trigger at each major version change

**Comment by onokatio** [comment]
Thanks for replying !

For the moment, I rebased branch with origin/dev and commited new config line.

I'm thinking about `metadata-from-title` in `youtube_dl_args`.
There are two ways to do this, one is to prepare two types of youtube_dl_args and choose one depending on whether video_mode is enabled or not. The other way is to set up a minimal set of video_dl_args and then add options to match the video_mode later.
How do you think?

**Comment by michaelb** [comment]
i think the best option would be to have two different sections.

The options between those would be quite different, and assuming an user wants to use aytdl to manage both music and video library, i'd them to have the freedom of configuring videos/music separately

I think introducing a switch in aytdl arguments for forcing video/music mode can also be a nice addition.

**Comment by onokatio** [comment]
That make sence. I'll implement separate config.

**Comment by michaelb** [comment]
if you don't understand everything that's going on (especially about config and its upgrade system), no worries: do what you can/want, I'll accept the PR on dev and fix stuff :-)

**Pull request closed without merging**
